"""
Namespaces associated with the moves api work.
"""
from rdflib.namespace import Namespace

# This provides a means of creating urns for each of the segments.  The urn should be generated by providing the
# startTime value for the segment to the end of this namespace.
MOVES_SEGMENT = Namespace('urn:moves-app.com:segment:')

EVENT = Namespace('http://purl.org/NET/c4dm/event.owl#')

SCHEMA = Namespace('http://schema.org/')

WGS_84 = Namespace('http://www.w3.org/2003/01/geo/wgs84_pos#')

LOCATION = Namespace('http://www.w3.org/ns/locn#')
